services:
  ladingpage-donadochopp:
    build:
      context: .
      dockerfile: Dockerfile
    pull_policy: build
    restart: always
    ports:
      - "8008:8008"
    # env_file:
    #   - stack.env
    networks:
      - pi_default
    volumes:
      - .:/app
      - dona_data:/var/lib/postgresql/data
      - dona_app:/app/media
volumes:
  dona_data:
  dona_app:
networks:
  pi_default:
    external: true