services:
  ladingpage2-chopp:
    build:
      context: .
      dockerfile: Dockerfile
    pull_policy: build
    restart: always
    ports:
      - "8010:8010"
    networks:
      - pi_default
    volumes:
      - ./db.sqlite3:/app/db.sqlite3
      - ./media:/app/media
networks:
  pi_default:
    external: true
