services:
  ladingpage2-chopp:
    build:
      context: .
      dockerfile: Dockerfile
    pull_policy: build
    restart: always
    ports:
      - "8010:8010"
    networks:
      - pi_default
    environment:
      - DJANGO_ENV=production
      - DJANGO_ALLOWED_HOSTS=vendas1.donadochopp.com.br,192.168.1.7,localhost,127.0.0.1
      - DJANGO_CSRF_TRUSTED_ORIGINS=https://vendas1.donadochopp.com.br,http://192.168.1.7:8010
      - MEDIA_ROOT=/app/media
      - MEDIA_URL=/media/
      - STATIC_ROOT=/app/staticfiles
      - STATIC_URL=/static/
      - SERVE_MEDIA=true
      - GUNICORN_WORKERS=2
      - GUNICORN_TIMEOUT=120
      - DB_NAME=cloudbooster_db
      - DB_USER=cloud_user
      - DB_PASSWORD=37192541aaSS@
      - DB_HOST=192.168.1.7
      - DB_PORT=5432
      - DB_SCHEMA=ladingpageddc
    volumes:
      - ladingpage2_chopp_app:/app/media
volumes:
  ladingpage2_chopp_app:
    name: ladingpage2_chopp_app
networks:
  pi_default:
    external: true
