version: '3.8'
services:
  web:
    build: .
    ports:
      - "8081:8081"
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html

    networks:
      - pi_default
networks:
  pi_default:
    external: true
