version: '3.8'
services:
  landingpage:
    image: nginx:latest
    volumes:
      - ./html:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/:ro  # Mudança feita para montar a pasta de configuração corretamente
    ports:
      - "8081:80"
    networks:
      - pi_default
networks:
  pi_default:
    external: true
