version: '3'
services:
  web:
    build: .
    ports:
      - "8081:80"
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html

    networks:
      - pi_default
networks:
  pi_default:
    external: true
