# Generated by Django 5.2.5 on 2025-08-16 03:26

import ckeditor.fields
import django.db.models.deletion
import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='produtos/')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', ckeditor.fields.RichTextField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estoque', models.PositiveIntegerField()),
                ('peso', models.DecimalField(decimal_places=2, help_text='Peso em kg', max_digits=5)),
                ('altura', models.DecimalField(decimal_places=2, help_text='Altura em cm', max_digits=5)),
                ('largura', models.DecimalField(decimal_places=2, help_text='Largura em cm', max_digits=5)),
                ('comprimento', models.DecimalField(decimal_places=2, help_text='Comprimento em cm', max_digits=5)),
                ('cep_origem', models.CharField(blank=True, default='58074158', max_length=9, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cliente', models.CharField(max_length=100)),
                ('cpf_cliente', models.CharField(max_length=11, unique=True)),
                ('endereco_cliente', models.CharField(max_length=255)),
                ('telefone_cliente', models.CharField(max_length=15)),
                ('email_cliente', models.EmailField(blank=True, max_length=100, null=True, unique=True)),
                ('data_nascimento_cliente', models.DateField()),
                ('quantidade', models.PositiveIntegerField()),
                ('data_pedido', models.DateTimeField(auto_now_add=True)),
                ('cor_produto', models.CharField(blank=True, max_length=50, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=home.models.logo_upload_path)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.produto')),
            ],
        ),
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagamento_id', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data', models.DateTimeField()),
                ('payment_type', models.CharField(blank=True, max_length=50, null=True)),
                ('nome_cliente', models.CharField(max_length=100)),
                ('cpf_cliente', models.CharField(max_length=11)),
                ('endereco_cliente', models.CharField(max_length=255)),
                ('telefone_cliente', models.CharField(max_length=15)),
                ('email_cliente', models.EmailField(blank=True, max_length=100, null=True)),
                ('data_nascimento_cliente', models.DateField()),
                ('quantidade', models.PositiveIntegerField()),
                ('data_pedido', models.DateTimeField(auto_now_add=True)),
                ('cor_produto', models.CharField(blank=True, max_length=50, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=home.models.logo_upload_path)),
                ('items', models.ManyToManyField(related_name='transacoes', to='home.produto')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.produto')),
            ],
        ),
    ]
