# Generated by Django 5.2.5 on 2025-08-16 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transacao',
            name='produto',
        ),
    ]
