# Generated by Django 5.2.5 on 2025-08-22 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_transacao_produto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='cor_produto',
            field=models.CharField(blank=True, choices=[('amarela_vermelha', 'Amarela e vermelha'), ('amarela_preta', 'Amarela e preta'), ('laranja_preta', 'Laranja e preta'), ('branca_preta', 'Branca e preta'), ('vermelha', 'Vermelha'), ('rosa_preta', 'Rosa e preta'), ('verde_branca', 'Verde e branca'), ('vermelha_preta', 'Vermelha e preta'), ('preta_verde', 'Preta e verde'), ('azul_vermelha', 'Azul e vermelha')], max_length=50, null=True),
        ),
    ]
