# Generated by Django 5.2.5 on 2026-05-26 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_pedido_cep_cliente_transacao_cep_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='eventos/')),
                ('categoria', models.CharField(default='Evento', max_length=80)),
                ('titulo', models.CharField(max_length=120)),
                ('descricao', models.CharField(blank=True, max_length=180)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['ordem', '-criado_em'],
            },
        ),
    ]
