# Generated by Django 5.2.5 on 2026-05-26 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_evento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Depoimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='depoimentos/')),
                ('tipo_midia', models.CharField(choices=[('video', 'Video'), ('imagem', 'Imagem')], max_length=10)),
                ('nome_cliente', models.CharField(max_length=100)),
                ('contexto', models.CharField(blank=True, max_length=120)),
                ('texto', models.CharField(blank=True, max_length=220)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Depoimento',
                'verbose_name_plural': 'Depoimentos',
                'ordering': ['ordem', '-criado_em'],
            },
        ),
    ]
