# Generated by Django 5.2.5 on 2026-05-26 21:52

import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_depoimento'),
    ]

    operations = [
        migrations.CreateModel(
            name='MidiaLanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(choices=[('hero_principal', 'Hero principal'), ('lucro_operacao', 'Lucro - operação'), ('video_thumb', 'Vídeo principal - capa'), ('video_principal', 'Vídeo principal - arquivo'), ('prova_social', 'Prova social'), ('galeria', 'Galeria'), ('logo_footer', 'Logo do rodapé')], max_length=40)),
                ('arquivo', models.FileField(upload_to=home.models.landing_media_upload_path)),
                ('tipo', models.CharField(choices=[('imagem', 'Imagem'), ('video', 'Vídeo')], default='imagem', max_length=10)),
                ('titulo', models.CharField(max_length=120)),
                ('descricao', models.CharField(blank=True, max_length=220)),
                ('link', models.URLField(blank=True)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Mídia da landing',
                'verbose_name_plural': 'Mídias da landing',
                'ordering': ['chave', 'ordem', '-criado_em'],
            },
        ),
    ]
