# Generated by Django 5.2.5 on 2026-06-02 16:08

import django.db.models.deletion
import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_seed_default_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecaoLanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Usado como identificador interno e na URL da seção.', max_length=80, unique=True)),
                ('ancora', models.CharField(blank=True, help_text='ID usado no menu/âncora. Se ficar vazio, usa o slug.', max_length=80)),
                ('tipo', models.CharField(choices=[('metricas_tabela', 'Texto, cards e tabela'), ('painel_destaque', 'Painel de destaque')], default='metricas_tabela', max_length=20)),
                ('etiqueta', models.CharField(blank=True, max_length=140)),
                ('titulo', models.CharField(max_length=220)),
                ('descricao', models.TextField(blank=True)),
                ('texto_final', models.TextField(blank=True)),
                ('observacao', models.TextField(blank=True)),
                ('imagem', models.FileField(blank=True, upload_to=home.models.landing_section_upload_path)),
                ('imagem_titulo', models.CharField(blank=True, max_length=140)),
                ('cabecalho_tabela_esquerda', models.CharField(blank=True, max_length=80)),
                ('cabecalho_tabela_direita', models.CharField(blank=True, max_length=80)),
                ('destaque_etiqueta', models.CharField(blank=True, max_length=140)),
                ('destaque_valor', models.CharField(blank=True, max_length=80)),
                ('destaque_descricao', models.CharField(blank=True, max_length=180)),
                ('destaque_observacao', models.TextField(blank=True)),
                ('fundo', models.CharField(choices=[('branco', 'Branco'), ('bege', 'Bege'), ('marrom', 'Marrom')], default='branco', max_length=10)),
                ('cor_titulo', models.CharField(choices=[('vermelho', 'Vermelho'), ('amarelo', 'Amarelo'), ('marrom', 'Marrom'), ('branco', 'Branco')], default='vermelho', max_length=10)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Seção da landing',
                'verbose_name_plural': 'Seções da landing',
                'ordering': ['ordem', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='SecaoLandingCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120)),
                ('valor', models.CharField(blank=True, max_length=80)),
                ('descricao', models.TextField(blank=True)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
                ('secao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='home.secaolanding')),
            ],
            options={
                'verbose_name': 'Card da seção',
                'verbose_name_plural': 'Cards da seção',
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SecaoLandingLinhaTabela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rotulo', models.CharField(max_length=140)),
                ('valor', models.CharField(max_length=80)),
                ('destacar', models.BooleanField(default=False)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
                ('secao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linhas_tabela', to='home.secaolanding')),
            ],
            options={
                'verbose_name': 'Linha de tabela da seção',
                'verbose_name_plural': 'Linhas de tabela da seção',
                'ordering': ['ordem', 'id'],
            },
        ),
    ]
