# Generated by Django 5.2.5 on 2026-06-02 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_seed_landing_sections'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='midialanding',
            options={'ordering': ['ordem', 'chave', '-criado_em'], 'verbose_name': 'Mídia da landing', 'verbose_name_plural': 'Mídias da landing'},
        ),
    ]
