# Generated by Django 5.2.5 on 2026-06-02 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_midialanding_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlocoFixoLanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(choices=[('produtos', 'Produtos'), ('eventos', 'Eventos'), ('passos', 'Como funciona'), ('beneficios', 'Benefícios'), ('video', 'Vídeo'), ('depoimentos', 'Depoimentos'), ('personalizar', 'Personalizar'), ('prova_social', 'Prova social'), ('galeria', 'Galeria'), ('faq', 'FAQ'), ('contato', 'Contato'), ('fechamento', 'Fechamento')], max_length=30, unique=True)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bloco fixo da landing',
                'verbose_name_plural': 'Blocos fixos da landing',
                'ordering': ['ordem', 'chave'],
            },
        ),
    ]
