# Generated by Django 5.2.5 on 2026-06-02 17:04

from django.db import migrations, models


def seed_trust_bar_block(apps, schema_editor):
    BlocoFixoLanding = apps.get_model("home", "BlocoFixoLanding")
    BlocoFixoLanding.objects.get_or_create(
        chave="barra_confianca",
        defaults={
            "ordem": 5,
            "ativo": True,
        },
    )


def remove_trust_bar_block(apps, schema_editor):
    BlocoFixoLanding = apps.get_model("home", "BlocoFixoLanding")
    BlocoFixoLanding.objects.filter(chave="barra_confianca").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_seed_fixed_landing_blocks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blocofixolanding',
            name='chave',
            field=models.CharField(choices=[('barra_confianca', 'Barra de confiança'), ('produtos', 'Produtos'), ('eventos', 'Eventos'), ('passos', 'Como funciona'), ('beneficios', 'Benefícios'), ('video', 'Vídeo'), ('depoimentos', 'Depoimentos'), ('personalizar', 'Personalizar'), ('prova_social', 'Prova social'), ('galeria', 'Galeria'), ('faq', 'FAQ'), ('contato', 'Contato'), ('fechamento', 'Fechamento')], max_length=30, unique=True),
        ),
        migrations.RunPython(seed_trust_bar_block, remove_trust_bar_block),
    ]
