# Generated by Django 5.2.5 on 2026-06-02 17:11

import django.db.models.deletion
import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_blocofixolanding_chave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secaolanding',
            name='tipo',
            field=models.CharField(choices=[('hero_principal', 'Hero principal'), ('barra_confianca', 'Barra de confiança'), ('produtos', 'Produtos'), ('metricas_tabela', 'Texto, cards e tabela'), ('painel_destaque', 'Painel de destaque'), ('eventos', 'Eventos'), ('passos', 'Como funciona'), ('beneficios', 'Benefícios'), ('video', 'Vídeo'), ('depoimentos', 'Depoimentos'), ('personalizar', 'Personalizar'), ('prova_social', 'Prova social'), ('galeria', 'Galeria'), ('faq', 'FAQ'), ('contato', 'Contato'), ('fechamento', 'Fechamento'), ('logo_footer', 'Logo do rodapé')], default='metricas_tabela', max_length=30),
        ),
        migrations.CreateModel(
            name='SecaoLandingMidia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to=home.models.landing_section_media_upload_path)),
                ('tipo', models.CharField(choices=[('imagem', 'Imagem'), ('video', 'Vídeo')], default='imagem', max_length=10)),
                ('papel', models.CharField(choices=[('principal', 'Principal'), ('capa', 'Capa do vídeo'), ('item', 'Item da galeria/lista')], default='principal', max_length=12)),
                ('titulo', models.CharField(blank=True, max_length=120)),
                ('descricao', models.CharField(blank=True, max_length=220)),
                ('link', models.URLField(blank=True)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('secao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='midias', to='home.secaolanding')),
            ],
            options={
                'verbose_name': 'Mídia da seção',
                'verbose_name_plural': 'Mídias da seção',
                'ordering': ['ordem', 'id'],
            },
        ),
    ]
