# Generated by Django 5.2.5 on 2026-06-02 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_seed_unified_landing_sections'),
    ]

    operations = [
        migrations.AddField(
            model_name='secaolanding',
            name='cor_titulo_destaque',
            field=models.CharField(choices=[('vermelho', 'Vermelho'), ('amarelo', 'Amarelo'), ('marrom', 'Marrom'), ('branco', 'Branco')], default='verde', help_text='Cor aplicada somente ao trecho destacado do título.', max_length=10),
        ),
        migrations.AddField(
            model_name='secaolanding',
            name='titulo_destaque',
            field=models.CharField(blank=True, help_text='Trecho do título que deve receber cor diferente.', max_length=160),
        ),
    ]
