# Generated by Django 5.2.5 on 2026-06-02 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_seed_title_highlight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secaolanding',
            name='cor_titulo_destaque',
            field=models.CharField(default='#169b4f', help_text='Cor aplicada ao trecho destacado. Use #169b4f, rgb(22,155,79), rgba(...) ou hsl(...).', max_length=40),
        ),
    ]
