# Generated by Django 5.2.5 on 2026-06-02 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_normalize_title_highlight_colors'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='secaolandingmidia',
            options={'ordering': ['-criado_em', '-id'], 'verbose_name': 'Mídia da seção', 'verbose_name_plural': 'Mídias da seção'},
        ),
    ]
