# Generated by Django 5.2.5 on 2026-06-02 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_alter_secaolandingmidia_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoLanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modo_black_friday', models.BooleanField(default=False)),
                ('texto_selo_black', models.CharField(blank=True, default='Black Friday', max_length=80)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração da landing',
                'verbose_name_plural': 'Configuração da landing',
            },
        ),
    ]
