# Generated by Django 5.2.5 on 2026-06-02 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_configuracaolanding'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaolanding',
            name='mostrar_barra_topo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='configuracaolanding',
            name='texto_barra_topo',
            field=models.CharField(blank=True, default='Oferta ativa: 10% off no PIX para todo o Brasil', max_length=140),
        ),
    ]
