# Generated by Django 5.2.5 on 2026-06-02 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_configuracaolanding_mostrar_barra_topo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='capital_retirada',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='pedido',
            name='tipo_entrega',
            field=models.CharField(choices=[('retirada_aeroporto', 'Retirada grátis no aeroporto da capital'), ('receber_em_casa', 'Receber em casa - chamar especialista')], default='retirada_aeroporto', max_length=30),
        ),
        migrations.AddField(
            model_name='transacao',
            name='capital_retirada',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='transacao',
            name='tipo_entrega',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
