# Generated by Django 5.2.5 on 2026-06-02 18:43

from django.db import migrations, models
from django.utils.text import slugify


def populate_product_slugs(apps, schema_editor):
    Produto = apps.get_model("home", "Produto")
    used_slugs = set()

    for produto in Produto.objects.order_by("id"):
        base_slug = slugify(produto.nome) or f"produto-{produto.id}"
        slug = base_slug
        counter = 2
        while slug in used_slugs or Produto.objects.exclude(id=produto.id).filter(slug=slug).exists():
            slug = f"{base_slug}-{counter}"
            counter += 1
        produto.slug = slug
        produto.save(update_fields=["slug"])
        used_slugs.add(slug)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_pedido_capital_retirada_pedido_tipo_entrega_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaolanding',
            name='url_publica_site',
            field=models.URLField(blank=True, help_text='URL pública usada em links enviados no WhatsApp. Ex: https://vendas1.donadochopp.com.br'),
        ),
        migrations.AddField(
            model_name='produto',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, null=True, unique=True),
        ),
        migrations.RunPython(populate_product_slugs, noop_reverse),
    ]
