# Generated by Django 5.2.5 on 2026-06-03 15:23

from django.db import migrations, models


def criar_secao_logo_header(apps, schema_editor):
    SecaoLanding = apps.get_model("home", "SecaoLanding")
    SecaoLanding.objects.get_or_create(
        slug="logo-header",
        defaults={
            "tipo": "logo_header",
            "titulo": "Logo do cabeçalho",
            "ordem": 140,
            "ativo": True,
        },
    )


def remover_secao_logo_header(apps, schema_editor):
    SecaoLanding = apps.get_model("home", "SecaoLanding")
    SecaoLanding.objects.filter(slug="logo-header", tipo="logo_header").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_configuracaolanding_url_publica_site_produto_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='midialanding',
            name='chave',
            field=models.CharField(choices=[('hero_principal', 'Hero principal'), ('lucro_operacao', 'Lucro - operação'), ('video_thumb', 'Vídeo principal - capa'), ('video_principal', 'Vídeo principal - arquivo'), ('prova_social', 'Prova social'), ('galeria', 'Galeria'), ('logo_header', 'Logo do cabeçalho'), ('logo_footer', 'Logo do rodapé')], max_length=40),
        ),
        migrations.AlterField(
            model_name='secaolanding',
            name='tipo',
            field=models.CharField(choices=[('hero_principal', 'Hero principal'), ('barra_confianca', 'Barra de confiança'), ('produtos', 'Produtos'), ('metricas_tabela', 'Texto, cards e tabela'), ('painel_destaque', 'Painel de destaque'), ('eventos', 'Eventos'), ('passos', 'Como funciona'), ('beneficios', 'Benefícios'), ('video', 'Vídeo'), ('depoimentos', 'Depoimentos'), ('personalizar', 'Personalizar'), ('prova_social', 'Prova social'), ('galeria', 'Galeria'), ('faq', 'FAQ'), ('contato', 'Contato'), ('fechamento', 'Fechamento'), ('logo_header', 'Logo do cabeçalho'), ('logo_footer', 'Logo do rodapé')], default='metricas_tabela', max_length=30),
        ),
        migrations.AlterField(
            model_name='secaolandingmidia',
            name='papel',
            field=models.CharField(choices=[('principal', 'Principal'), ('desktop', 'Desktop'), ('mobile', 'Mobile'), ('logo_header', 'Logo do cabeçalho'), ('capa', 'Capa do vídeo'), ('item', 'Item da galeria/lista')], default='principal', max_length=12),
        ),
        migrations.RunPython(criar_secao_logo_header, remover_secao_logo_header),
    ]
