# Generated by Django 5.2.5 on 2026-06-04 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_relax_customer_reorder_require_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacao',
            name='produto_variacao_nome',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='ProdutoVariacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('cor_hex', models.CharField(blank=True, help_text='Opcional. Ex: #df2f24', max_length=20)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='produtos/variacoes/')),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variacoes', to='home.produto')),
            ],
            options={
                'verbose_name': 'Variação do produto',
                'verbose_name_plural': 'Variações do produto',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.AddField(
            model_name='pedido',
            name='produto_variacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='home.produtovariacao'),
        ),
    ]
