# Generated by Django 5.2.5 on 2026-06-04 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_transacao_produto_variacao_nome_produtovariacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='solicitar_logo',
            field=models.BooleanField(default=True, help_text='Marque apenas para produtos que precisam receber logomarca no checkout.'),
        ),
    ]
